const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('desktop', {
  modal: open => ipcRenderer.invoke('window:modal', open),
  theme: dark => ipcRenderer.invoke('window:theme', dark),
  onHistory: callback => ipcRenderer.on('document:history', (_event, redo) => callback(redo)),
  recent: () => ipcRenderer.invoke('document:recent'),
  openRecent: file => ipcRenderer.invoke('document:open-recent', file),
  dismissPending: file => ipcRenderer.invoke('document:dismiss-pending', file),
  pending: () => ipcRenderer.invoke('document:pending'),
  openPending: file => ipcRenderer.invoke('document:open-pending', file),
  onOpenRequest: callback => ipcRenderer.on('document:requested', callback),
  about: () => ipcRenderer.invoke('app:about'),
  openExternal: url => ipcRenderer.invoke('app:open-external', url),
  onShowAbout: callback => ipcRenderer.on('app:show-about', (_event, checkNow) => callback(checkNow)),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdateAvailable: callback => ipcRenderer.on('update:available', (_event, result) => callback(result)),
  onUpdateProgress: callback => ipcRenderer.on('update:progress', (_event, value) => callback(value)),
  open: () => ipcRenderer.invoke('document:open'),
  save: (content, saveAs, format) => ipcRenderer.invoke('document:save', { content, saveAs, format }),
  newDocument: () => ipcRenderer.invoke('document:new'),
  image: mode => ipcRenderer.invoke('document:image', mode),
  pdf: () => ipcRenderer.invoke('document:pdf'),
  dirty: value => ipcRenderer.send('document:dirty', value),
});
