import { chromium } from '@playwright/test';
import { readFileSync, writeFileSync } from 'node:fs';
const browser = await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage(); const svg=readFileSync('build/icon.svg','utf8'); const chunks=[], pngs={};
// The arrow overlaps the M at Dock/menu sizes. Keep only the mark in small icons.
const smallSvg = svg.replace(/<path d="M328 376[^>]+\/>/, '');
for(const size of [16,32,48,64,128,256,512,1024]) { await page.setViewportSize({width:size,height:size}); await page.setContent(`<style>html,body{width:100%;height:100%;margin:0}svg{display:block;width:100%;height:100%}</style>${size<=64?smallSvg:svg}`); const png=await page.screenshot({omitBackground:true}); pngs[size]=png; if(size===512)writeFileSync('build/icon.png',png);else if(size<512)chunks.push({size,png}); }
// macOS doesn't decode PNG in the 16/32 px slots (icp4/icp5); use ARGB like iconutil does.
const packBits=bytes=>{const out=[];for(let i=0;i<bytes.length;){let run=1;while(run<130&&i+run<bytes.length&&bytes[i+run]===bytes[i])run++;if(run>=3){out.push(0x80+run-3,bytes[i]);i+=run;continue;}let start=i;while(i<bytes.length&&i-start<128&&!(i+2<bytes.length&&bytes[i]===bytes[i+1]&&bytes[i]===bytes[i+2]))i++;out.push(i-start-1,...bytes.slice(start,i));}return out;};
const argb=async size=>{const rgba=await page.evaluate(async src=>{const img=new Image();img.src=src;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);return [...ctx.getImageData(0,0,c.width,c.height).data];},`data:image/png;base64,${pngs[size].toString('base64')}`);const channels=[3,0,1,2].map(ch=>rgba.filter((_,i)=>i%4===ch));return Buffer.concat([Buffer.from('ARGB'),...channels.map(c=>Buffer.from(packBits(c)))]);};
const icnsData={ic04:await argb(16),ic05:await argb(32),ic07:pngs[128],ic08:pngs[256],ic09:pngs[512],ic10:pngs[1024],ic11:pngs[32],ic12:pngs[64],ic13:pngs[256],ic14:pngs[512]};
const icns=Object.entries(icnsData).map(([type,data])=>{const h=Buffer.alloc(8);h.write(type,0,'ascii');h.writeUInt32BE(data.length+8,4);return Buffer.concat([h,data]);});
const icnsHeader=Buffer.alloc(8);icnsHeader.write('icns',0,'ascii');icnsHeader.writeUInt32BE(8+icns.reduce((n,b)=>n+b.length,0),4);writeFileSync('build/icon.icns',Buffer.concat([icnsHeader,...icns]));
let offset=6+16*chunks.length;const header=Buffer.alloc(offset);header.writeUInt16LE(1,2);header.writeUInt16LE(chunks.length,4);chunks.forEach(({size,png},i)=>{let p=6+i*16;header[p]=size%256;header[p+1]=size%256;header.writeUInt16LE(1,p+4);header.writeUInt16LE(32,p+6);header.writeUInt32LE(png.length,p+8);header.writeUInt32LE(offset,p+12);offset+=png.length});writeFileSync('build/icon.ico',Buffer.concat([header,...chunks.map(x=>x.png)])); await browser.close();
