import './style.css';
import 'katex/dist/katex.min.css';
import 'highlight.js/styles/github.css';
import { renderDocument } from './render';
import { sample } from './sample';
const api = window.desktop;
const $ = s => document.querySelector(s);
let name = '欢迎使用 Mardar.md', base = '', saved = sample, format = 'markdown', version = 0, rendering = Promise.resolve(), timer;
let draft; try { draft = JSON.parse(localStorage.getItem('mardar-draft')); } catch {}
$('#app').innerHTML = `<aside class="sidebar"><div class="brand"><span class="logo">M<span>·</span></span><strong>Mardar</strong></div><div class="workspace-label">个人写作空间</div><button class="new" id="new">＋ 新建文档 <kbd>⌘ N</kbd></button><button class="open" id="open">▱ 打开本地文件</button><div class="nav-label">当前文档</div><div class="active-doc">▤ <span id="side-name"></span></div><div class="outline-header">文档大纲 <span>≡</span></div><nav id="outline"></nav><div class="sidebar-footer"><span class="online"></span> 本地优先 · 自由创作<small>Markdown & HTML 编辑器</small></div></aside><main><header><div class="breadcrumb">写作空间 <span>/</span> <b id="name"></b><i id="dirty"></i></div><div class="actions"><button id="save">保存</button><button id="save-as">另存为</button><button class="primary" id="pdf">↓ 导出 PDF</button></div></header><section class="toolbar"><div class="format-tools"><button data-wrap="**" title="粗体">B</button><button data-wrap="*" title="斜体"><i>I</i></button><button data-prefix="## " title="标题">H₂</button><span class="divider"></span><button data-prefix="> " title="引用">❞</button><button data-prefix="- " title="列表">☷</button><button id="link" title="插入链接">↗</button><button id="image" title="插入图片">▧</button><button id="code" title="代码块">&lt;/&gt;</button><button id="math" title="数学公式">ƒx</button><button id="chart" title="Mermaid 图表">◇</button></div><div class="view-tools"><select id="format" aria-label="文档格式"><option value="markdown">Markdown</option><option value="html">HTML</option></select><button data-view="edit">编辑</button><button class="selected" data-view="split">分栏</button><button data-view="read">阅读</button><button id="theme" title="切换深色主题">◐</button></div></section><section class="panes" data-view="split"><div class="editor-pane"><div class="pane-label">源文档 <span>纯粹书写，自由表达</span></div><textarea id="editor" spellcheck="false" aria-label="文档编辑器"></textarea></div><div class="preview-pane"><div class="pane-label">实时预览 <span>✦ 所见即所得</span></div><div id="preview"></div></div></section><footer><span id="status">准备就绪</span><span><span id="count"></span><span class="footer-divider">|</span>UTF-8<span class="footer-divider">|</span><span id="position">行 1，列 1</span></span></footer></main><input type="file" id="file" accept=".md,.markdown,.html,.htm" hidden><input type="file" id="image-file" accept="image/*" hidden><dialog id="confirm"><h2>保存当前更改？</h2><p>离开当前文档前，可以保存你的写作内容。</p><div><button data-choice="cancel">取消</button><button data-choice="discard">不保存</button><button class="primary" data-choice="save">保存</button></div></dialog>`;
if (!/Mac/.test(navigator.platform)) $('.new kbd').textContent = 'Ctrl N';
const editor = $('#editor'); editor.value = draft?.content ?? sample;
if (draft) { name = draft.name; format = draft.format; }
$('#format').value = format;
function status(text) { $('#status').textContent = text; }
function metadata() { $('#name').textContent = name; $('#side-name').textContent = name; $('#dirty').textContent = editor.value !== saved ? '●' : ''; document.title = `${name} · Mardar`; api?.dirty(editor.value !== saved); $('#count').textContent = `${editor.value.replace(/\s/g, '').length.toLocaleString()} 字符`; }
function persist() { try { localStorage.setItem('mardar-draft', JSON.stringify({ content: editor.value, name, format })); } catch { status('草稿存储已满，请保存到文件'); } }
function render() { const id = ++version; rendering = renderDocument(editor.value, format, base).then(root => { if (id !== version) return; $('#preview').replaceChildren(root); $('#outline').replaceChildren(); root.querySelectorAll('h1,h2,h3').forEach(h => { const b = document.createElement('button'); b.textContent = h.textContent; b.className = h.tagName.toLowerCase(); b.onclick = () => h.scrollIntoView({ behavior: 'smooth' }); $('#outline').append(b); }); }); return rendering; }
function changed() { metadata(); persist(); clearTimeout(timer); timer = setTimeout(() => render().catch(e => status(e.message)), 220); }
editor.addEventListener('input', changed);
editor.addEventListener('keyup', () => { const lines = editor.value.slice(0, editor.selectionStart).split('\n'); $('#position').textContent = `行 ${lines.length}，列 ${lines.at(-1).length + 1}`; });
function insert(text, suffix = '') { const selected = editor.value.slice(editor.selectionStart, editor.selectionEnd); editor.focus(); document.execCommand('insertText', false, text + selected + suffix); changed(); }
document.querySelectorAll('[data-wrap]').forEach(b => b.onclick = () => { const tag = b.dataset.wrap === '**' ? 'strong' : 'em'; insert(format === 'html' ? `<${tag}>` : b.dataset.wrap, format === 'html' ? `</${tag}>` : b.dataset.wrap); });
document.querySelectorAll('[data-prefix]').forEach(b => b.onclick = () => { const tag = { '## ': 'h2', '> ': 'blockquote', '- ': 'li' }[b.dataset.prefix]; insert(format === 'html' ? `<${tag}>` : b.dataset.prefix, format === 'html' ? `</${tag}>` : ''); });
$('#link').onclick = () => format === 'html' ? insert('<a href="https://example.com">', '</a>') : insert('[', '](https://example.com)');
$('#code').onclick = () => format === 'html' ? insert('<pre><code>', '</code></pre>') : insert('\n```javascript\n', '\n```\n');
$('#math').onclick = () => insert('\n$$\n', '\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}\n$$\n');
$('#chart').onclick = () => format === 'html' ? insert('<pre class="mermaid">graph LR\n  A[开始] --&gt; B[完成]</pre>') : insert('\n```mermaid\ngraph LR\n  A[开始] --> B[完成]\n```\n');
document.querySelectorAll('[data-view]').forEach(b => { if (b.tagName !== 'BUTTON') return; b.onclick = () => { $('.panes').dataset.view = b.dataset.view; document.querySelectorAll('.view-tools [data-view]').forEach(x => x.classList.toggle('selected', x === b)); }; });
$('#theme').onclick = () => document.body.classList.toggle('dark');
$('#format').onchange = () => { format = $('#format').value; changed(); };
function download(content, filename, type) { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([content], { type })); a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }
async function save(saveAs = false) { try { const content = editor.value; const result = api ? await api.save(content, saveAs, format) : { name }; if (!result) return false; if (!api) download(content, name, 'text/plain;charset=utf-8'); name = result.name; base = result.base || ''; saved = content; metadata(); persist(); await render(); status('文档已保存'); return true; } catch (e) { status(`保存失败：${e.message}`); return false; } }
async function mayLeave() { if (editor.value === saved) return true; const choice = await new Promise(resolve => { const d = $('#confirm'); d.showModal(); d.oncancel = e => { e.preventDefault(); d.close(); resolve('cancel'); }; d.querySelectorAll('button').forEach(b => b.onclick = () => { d.close(); resolve(b.dataset.choice); }); }); return choice === 'discard' || (choice === 'save' && await save()); }
async function load(doc) { editor.value = doc.content; saved = doc.content; name = doc.name; base = doc.base || ''; format = doc.format; $('#format').value = format; changed(); await render(); }
$('#save').onclick = () => save(); $('#save-as').onclick = () => save(true);
$('#new').onclick = async () => { if (!await mayLeave()) return; await api?.newDocument(); await load({ content: '', name: '未命名.md', format: 'markdown' }); editor.focus(); };
$('#open').onclick = async () => { if (!await mayLeave()) return; try { if (api) { const doc = await api.open(); if (doc) await load(doc); } else $('#file').click(); } catch (e) { status(`打开失败：${e.message}`); } };
$('#file').onchange = async e => { const f = e.target.files[0]; if (f) await load({ content: await f.text(), name: f.name, format: /\.html?$/i.test(f.name) ? 'html' : 'markdown' }); e.target.value = ''; };
function addImage(item) { insert(format === 'html' ? `<img alt="图片" src="${item.url}">` : `![图片](${item.url})`); }
function readImage(file) { const reader = new FileReader(); reader.onload = () => addImage({ url: reader.result }); reader.readAsDataURL(file); }
$('#image').onclick = async () => { try { if (api) { const item = await api.image(); if (item) addImage(item); } else $('#image-file').click(); } catch (e) { status(e.message); } };
$('#image-file').onchange = e => { if (e.target.files[0]) readImage(e.target.files[0]); e.target.value = ''; };
editor.addEventListener('dragover', e => e.preventDefault()); editor.addEventListener('drop', e => { e.preventDefault(); for (const f of e.dataTransfer.files) if (f.type.startsWith('image/')) readImage(f); });
editor.addEventListener('paste', e => { const images = [...e.clipboardData.files].filter(f => f.type.startsWith('image/')); if (images.length) { e.preventDefault(); images.forEach(readImage); } });
$('#pdf').onclick = async () => { const button = $('#pdf'); button.disabled = true; status('正在排版 PDF…'); try { clearTimeout(timer); await render(); await document.fonts.ready; await Promise.all([...$('#preview').querySelectorAll('img')].map(img => img.decode().catch(() => {}))); if (api) { const path = await api.pdf(); status(path ? `PDF 已导出：${path}` : '已取消导出'); } else { window.print(); status('已打开打印对话框，请选择保存为 PDF'); } } catch (e) { status(`导出失败：${e.message}`); } finally { button.disabled = false; } };
document.addEventListener('keydown', e => { if (!(e.metaKey || e.ctrlKey)) return; const key = e.key.toLowerCase(); if (['s', 'o', 'n', 'b', 'i'].includes(key)) { e.preventDefault(); if (key === 's') save(e.shiftKey); if (key === 'o') $('#open').click(); if (key === 'n') $('#new').click(); if (key === 'b') document.querySelectorAll('[data-wrap]')[0].click(); if (key === 'i') document.querySelectorAll('[data-wrap]')[1].click(); } });
window.addEventListener('beforeunload', e => { if (!api && editor.value !== saved) { e.preventDefault(); e.returnValue = ''; } });
metadata(); render().catch(e => status(e.message));
