import MarkdownIt from 'markdown-it';
import texmath from 'markdown-it-texmath';
import katex from 'katex';
import renderMathInElement from 'katex/contrib/auto-render';
import hljs from 'highlight.js';
import DOMPurify from 'dompurify';
import mermaid from 'mermaid';
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict', theme: 'neutral', htmlLabels: false, flowchart: { htmlLabels: false } });
const md = new MarkdownIt({ html: true, linkify: true, typographer: true, highlight(code, lang) {
  return lang && hljs.getLanguage(lang) ? hljs.highlight(code, { language: lang }).value : md.utils.escapeHtml(code);
}}).use(texmath, { engine: katex, delimiters: 'dollars', katexOptions: { throwOnError: false, trust: false } });
const validateLink = md.validateLink;
md.validateLink = url => /^data:image\/(?:png|jpeg|gif|webp|svg\+xml);base64,[a-z0-9+/=]+$/i.test(url) || validateLink(url);
const fence = md.renderer.rules.fence;
md.renderer.rules.fence = (tokens, i, options, env, self) => tokens[i].info.trim() === 'mermaid' ? `<pre class="mermaid">${md.utils.escapeHtml(tokens[i].content)}</pre>` : fence(tokens, i, options, env, self);
let counter = 0;
export async function renderDocument(source, format, base) {
  const root = document.createElement('article'); root.className = 'prose';
  root.innerHTML = DOMPurify.sanitize(format === 'html' ? source : md.render(source), { ADD_TAGS: ['eq', 'eqn', 'annotation', 'semantics'], ADD_ATTR: ['encoding'], FORBID_TAGS: ['style', 'input', 'form'], FORBID_ATTR: ['style', 'srcset'] });
  // Restore only styles generated by KaTeX after removing document-provided CSS.
  for (const formula of root.querySelectorAll('.katex')) {
    const expression = formula.querySelector('annotation[encoding="application/x-tex"]')?.textContent;
    if (expression) {
      const displayMode = formula.parentElement.classList.contains('katex-display');
      const span = document.createElement('span');
      katex.render(expression, span, { throwOnError: false, trust: false, displayMode });
      (displayMode ? formula.parentElement : formula).replaceWith(span);
    }
  }
  if (format === 'html') renderMathInElement(root, { delimiters: [{ left: '$$', right: '$$', display: true }, { left: '$', right: '$', display: false }], throwOnError: false, trust: false, ignoredClasses: ['katex'] });
  for (const img of root.querySelectorAll('img')) {
    const src = img.getAttribute('src');
    if (base && src && !/^[a-z]+:|^\/\//i.test(src)) img.src = new URL(src, base).href;
    img.addEventListener('error', () => { img.alt = `图片无法加载：${img.alt || src}`; });
  }
  for (const node of root.querySelectorAll('.mermaid')) {
    const id = `diagram-${++counter}`;
    try { const { svg } = await mermaid.render(id, node.textContent); node.innerHTML = DOMPurify.sanitize(svg, { USE_PROFILES: { svg: true, svgFilters: true, html: true } }); }
    catch { document.getElementById(`d${id}`)?.remove(); node.className = 'diagram-error'; node.textContent = '图表语法有误，请检查 Mermaid 代码。'; }
  }
  root.querySelectorAll('h1,h2,h3').forEach((el, i) => el.id = `heading-${i}`);
  root.querySelectorAll('a').forEach(a => { a.addEventListener('click', event => { event.preventDefault(); if (a.hash) document.getElementById(a.hash.slice(1))?.scrollIntoView({ behavior: 'smooth' }); }); });
  return root;
}
