import MarkdownIt from 'markdown-it';
import texmath from 'markdown-it-texmath';
import katex from 'katex';
import hljs from 'highlight.js';
import DOMPurify from 'dompurify';
import mermaid from 'mermaid';
mermaid.initialize({ startOnLoad: false, securityLevel: 'strict', theme: 'neutral', htmlLabels: false, flowchart: { htmlLabels: false } });
const md = new MarkdownIt({ html: true, linkify: true, typographer: true, highlight(code, lang) {
  return lang && hljs.getLanguage(lang) ? hljs.highlight(code, { language: lang }).value : md.utils.escapeHtml(code);
}}).use(texmath, { engine: katex, delimiters: 'dollars', katexOptions: { throwOnError: false, trust: false } });
const validateLink = md.validateLink;
// Local image references are useful in desktop documents; other file attributes
// still pass through the normal sanitizer.
DOMPurify.addHook('uponSanitizeAttribute', (node, data) => {
  if (node.tagName === 'IMG' && data.attrName === 'src' && /^file:\/\//i.test(data.attrValue)) data.forceKeepAttr = true;
});
md.validateLink = url => /^file:\/\//i.test(url) || /^data:image\/(?:png|jpeg|gif|webp|svg\+xml);base64,[a-z0-9+/=]+$/i.test(url) || validateLink(url);
md.core.ruler.push('source_positions', state => {
  for (const token of state.tokens) if (token.map && token.nesting !== -1) {
    token.attrSet('data-source-line', String(token.map[0]));
    token.attrSet('data-source-end', String(token.map[1]));
  }
});
const fence = md.renderer.rules.fence;
md.renderer.rules.fence = (tokens, i, options, env, self) => tokens[i].info.trim() === 'mermaid' ? `<pre class="mermaid" data-source-line="${tokens[i].map[0]}" data-source-end="${tokens[i].map[1]}">${md.utils.escapeHtml(tokens[i].content)}</pre>` : fence(tokens, i, options, env, self);
let counter = 0;
export async function renderDocument(source, format, base) {
  const root = document.createElement('article'); root.className = 'prose';
  root.innerHTML = DOMPurify.sanitize(md.render(source), { ADD_TAGS: ['eq', 'eqn', 'annotation', 'semantics'], ADD_ATTR: ['encoding'], FORBID_TAGS: ['style', 'input', 'form'], FORBID_ATTR: ['style', 'srcset'] });
  const raw = document.createElement('template'); raw.innerHTML = DOMPurify.sanitize(md.render(source));
  const originals = [...raw.content.querySelectorAll('img')];
  root.querySelectorAll('img').forEach((img, i) => {
    const style = originals[i]?.style;
    for (const key of ['zoom', 'width', 'height', 'maxWidth']) {
      const value = style?.[key];
      if (value && /^(?:[0-9]+(?:\.[0-9]+)?(?:%|px|em|rem)?|auto)$/.test(value)) img.style[key] = value;
    }
  });
  // Restore only styles generated by KaTeX after removing document-provided CSS.
  for (const formula of root.querySelectorAll('.katex')) {
    const expression = formula.querySelector('annotation[encoding="application/x-tex"]')?.textContent;
    if (expression) {
      const displayMode = formula.parentElement.classList.contains('katex-display');
      const span = document.createElement('span');
      katex.render(expression, span, { throwOnError: false, trust: false, displayMode });
      (displayMode ? formula.parentElement : formula).replaceWith(span);
    }
  }

  for (const img of root.querySelectorAll('img')) {
    const src = img.getAttribute('src');
    if (base && src && !/^[a-z]+:|^\/\//i.test(src)) img.src = new URL(src, base).href;
    img.addEventListener('error', () => { img.alt = `图片无法加载：${img.alt || src}`; });
  }
  for (const node of root.querySelectorAll('.mermaid')) {
    const id = `diagram-${++counter}`;
    try { const { svg } = await mermaid.render(id, node.textContent); node.innerHTML = DOMPurify.sanitize(svg, { USE_PROFILES: { svg: true, svgFilters: true, html: true } }); }
    catch { document.getElementById(`d${id}`)?.remove(); node.className = 'diagram-error'; node.textContent = '图表语法有误，请检查 Mermaid 代码。'; }
  }
  root.querySelectorAll('h1,h2,h3').forEach((el, i) => el.id = `heading-${i}`);
  root.querySelectorAll('a').forEach(a => { a.addEventListener('click', event => { event.preventDefault(); if (a.hash) document.getElementById(a.hash.slice(1))?.scrollIntoView({ behavior: 'smooth' }); }); });
  return root;
}

export function sourceBlocks(source) {
  const lines = source.split('\n'), offsets = [0];
  for (const line of lines) offsets.push(offsets.at(-1) + line.length + 1);
  const starts = [...new Set(md.parse(source, {}).filter(t => t.level === 0 && t.map).map(t => offsets[t.map[0]]))];
  if (starts[0] !== 0) starts.unshift(0);
  return starts.map((start, i) => ({ start, text: source.slice(start, starts[i + 1] ?? source.length) }));
}
